export const SHOW_PRODUCT_IN_CART = "SHOW_PRODUCT_IN_CART";
export const HIDE_PRODUCT_IN_CART = "HIDE_PRODUCT_IN_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";
